---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[instrumental::default]
    attributes:
      instrumental:
        api_key: "fake-key"
